<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Form\Type\QuickNavigation;

use Paustian\RatingsModule\Form\Type\QuickNavigation\Base\AbstractRatingSystemQuickNavType;

/**
 * Rating system quick navigation form type implementation class.
 */
class RatingSystemQuickNavType extends AbstractRatingSystemQuickNavType
{
    // feel free to extend the base form type class here
}
