<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Form\Type\QuickNavigation;

use Paustian\RatingsModule\Form\Type\QuickNavigation\Base\AbstractRatingQuickNavType;

/**
 * Rating quick navigation form type implementation class.
 */
class RatingQuickNavType extends AbstractRatingQuickNavType
{
    // feel free to extend the base form type class here
}
