<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Event;

use Paustian\RatingsModule\Event\Base\AbstractRatingPrePersistEvent;

/**
 * Event implementation class for filtering rating processing.
 */
class RatingPrePersistEvent extends AbstractRatingPrePersistEvent
{
    // feel free to extend the event class here
}
