<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Helper;

use Paustian\RatingsModule\Helper\Base\AbstractPermissionHelper;

/**
 * Permission helper implementation class.
 */
class PermissionHelper extends AbstractPermissionHelper
{
    // feel free to extend the permission helper here
}
