<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Event\Base;

use Paustian\RatingsModule\Entity\RatingEntity;
use Symfony\Component\EventDispatcher\Event;

/**
 * Event base class for filtering rating processing.
 */
class AbstractFilterRatingEvent extends Event
{
    /**
     * @var RatingEntity Reference to treated entity instance.
     */
    protected $rating;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    public function __construct(RatingEntity $rating, array $entityChangeSet = [])
    {
        $this->rating = $rating;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * @return RatingEntity
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }

    /**
     * @param array $changeSet Entity change set
     */
    public function setEntityChangeSet(array $changeSet = [])
    {
        $this->entityChangeSet = $changeSet;
    }
}
