services:
    # Event subscribers and listeners
    paustian_ratings_module.entity_lifecycle_listener:
        class: Paustian\RatingsModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags: ['doctrine.event_subscriber']
    
    paustian_ratings_module.kernel_listener:
        class: Paustian\RatingsModule\Listener\KernelListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.installer_listener:
        class: Paustian\RatingsModule\Listener\InstallerListener
        arguments:
            - "@paustian_ratings_module.entity_factory"
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.moduledispatch_listener:
        class: Paustian\RatingsModule\Listener\ModuleDispatchListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.mailer_listener:
        class: Paustian\RatingsModule\Listener\MailerListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.theme_listener:
        class: Paustian\RatingsModule\Listener\ThemeListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.userlogin_listener:
        class: Paustian\RatingsModule\Listener\UserLoginListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.userlogout_listener:
        class: Paustian\RatingsModule\Listener\UserLogoutListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.user_listener:
        class: Paustian\RatingsModule\Listener\UserListener
        arguments:
            - "@translator.default"
            - "@paustian_ratings_module.entity_factory"
            - "@zikula_users_module.current_user"
            - "@logger"
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.userregistration_listener:
        class: Paustian\RatingsModule\Listener\UserRegistrationListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.users_listener:
        class: Paustian\RatingsModule\Listener\UsersListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.group_listener:
        class: Paustian\RatingsModule\Listener\GroupListener
        tags: ['kernel.event_subscriber']
    
    paustian_ratings_module.workflow_events_listener:
        class: Paustian\RatingsModule\Listener\WorkflowEventsListener
        arguments:
            - "@paustian_ratings_module.entity_factory"
            - "@paustian_ratings_module.permission_helper"
        tags: ['kernel.event_subscriber']
    
