services:
    # Custom validators
    paustian_ratings_module.validator.list_entry.validator:
        class: Paustian\RatingsModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@paustian_ratings_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: paustian_ratings_module.validator.list_entry.validator }
