services:
    # Helper services
    paustian_ratings_module.collection_filter_helper:
        class: Paustian\RatingsModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@paustian_ratings_module.permission_helper"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').get('PaustianRatingsModule', 'showOnlyOwnEntries', false)"
    
    paustian_ratings_module.controller_helper:
        class: Paustian\RatingsModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@router"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@paustian_ratings_module.entity_factory"
            - "@paustian_ratings_module.collection_filter_helper"
            - "@paustian_ratings_module.permission_helper"
            - "@paustian_ratings_module.model_helper"
    
    paustian_ratings_module.entity_display_helper:
        class: Paustian\RatingsModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@paustian_ratings_module.listentries_helper"
    
    paustian_ratings_module.listentries_helper:
        class: Paustian\RatingsModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    paustian_ratings_module.model_helper:
        class: Paustian\RatingsModule\Helper\ModelHelper
        arguments:
            - "@paustian_ratings_module.entity_factory"
    
    paustian_ratings_module.permission_helper:
        class: Paustian\RatingsModule\Helper\PermissionHelper
        arguments:
            - "@service_container"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@zikula_users_module.user_repository"
    
    paustian_ratings_module.view_helper:
        class: Paustian\RatingsModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@paustian_ratings_module.controller_helper"
            - "@paustian_ratings_module.permission_helper"
    
    paustian_ratings_module.workflow_helper:
        class: Paustian\RatingsModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@paustian_ratings_module.entity_factory"
            - "@paustian_ratings_module.listentries_helper"
            - "@paustian_ratings_module.permission_helper"
