services:
    # Twig extension
    paustian_ratings_module.twig_extension:
        class: Paustian\RatingsModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@paustian_ratings_module.entity_display_helper"
            - "@paustian_ratings_module.workflow_helper"
            - "@paustian_ratings_module.listentries_helper"
        public: false
        tags: ['twig.extension']
