<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Form\Type;

use Paustian\RatingsModule\Form\Type\Base\AbstractRatingSystemType;

/**
 * Rating system editing form type implementation class.
 */
class RatingSystemType extends AbstractRatingSystemType
{
    // feel free to extend the rating system editing form type class here
}
