<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule;

use Paustian\RatingsModule\Base\AbstractRatingsModuleInstaller;

/**
 * Installer implementation class.
 */
class RatingsModuleInstaller extends AbstractRatingsModuleInstaller
{
    // feel free to extend the installer here
}
