<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Entity;

use Paustian\RatingsModule\Entity\Base\AbstractHookAssignmentEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity implementation class for hooked object assignments.
 *
 * @ORM\Entity()
 * @ORM\Table(name="paustian_rating_hookassignment")
 */
class HookAssignmentEntity extends AbstractHookAssignmentEntity
{
    // feel free to add your own methods here
}
