<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 *
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Form\Handler\Rating;

use Paustian\RatingsModule\Form\Handler\Rating\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the rating object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
