<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Event;

use Paustian\RatingsModule\Event\Base\AbstractConfigureItemActionsMenuEvent;

/**
 * Event implementation class for extending item actions menu.
 */
class ConfigureItemActionsMenuEvent extends AbstractConfigureItemActionsMenuEvent
{
    // feel free to extend the event class here
}
