<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Listener;

use Paustian\RatingsModule\Listener\Base\AbstractUserListener;

/**
 * Event handler implementation class for user-related events.
 */
class UserListener extends AbstractUserListener
{
    // feel free to enhance the parent methods
}
