<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Entity;

use Paustian\RatingsModule\Entity\Base\AbstractRatingSystemEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for rating system entities.
 * @ORM\Entity(repositoryClass="Paustian\RatingsModule\Entity\Repository\RatingSystemRepository")
 * @ORM\Table(name="paustian_rating_ratingsystem",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class RatingSystemEntity extends BaseEntity
{
    // feel free to add your own methods here
}
