<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 *
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Twig\Base;

use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;
use Paustian\RatingsModule\Twig\TwigRuntime;

/**
 * Twig extension base class.
 */
abstract class AbstractTwigExtension extends AbstractExtension
{
    public function getFunctions()
    {
        return [
            new TwigFunction('paustianratingsmodule_objectTypeSelector', [TwigRuntime::class, 'getObjectTypeSelector']),
            new TwigFunction('paustianratingsmodule_templateSelector', [TwigRuntime::class, 'getTemplateSelector']),
        ];
    }
    
    public function getFilters()
    {
        return [
            new TwigFilter('paustianratingsmodule_listEntry', [TwigRuntime::class, 'getListEntry']),
            new TwigFilter('paustianratingsmodule_formattedTitle', [TwigRuntime::class, 'getFormattedEntityTitle']),
            new TwigFilter('paustianratingsmodule_objectState', [TwigRuntime::class, 'getObjectState'], ['is_safe' => ['html']]),
        ];
    }
}
