<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Zikula\ThemeModule\Engine\Annotation\Theme;
use Paustian\RatingsModule\Controller\Base\AbstractConfigController;

/**
 * Config controller implementation class.
 *
 * @Route("/config")
 */
class ConfigController extends AbstractConfigController
{
    /**
     * @Route("/config",
     *        methods = {"GET", "POST"}
     * )
     * @Theme("admin")
     */
    public function configAction(Request $request)
    {
        $oldRating = $this->getVar('ratingScale');
        $result = parent::configAction($request);
        $newRating = $this->getVar('ratingScale');
        $em = $this->getDoctrine()->getManager();
        if($oldRating !== $newRating){
            $ratingObjs =$em->getRepository('Paustian\RatingsModule\Entity\RatingEntity')->findAll();
            $ratio = $newRating/$oldRating;
            foreach($ratingObjs as $ratingObj){
                $newRating = $ratingObj->getRating() * $ratio;
                $ratingObj->setRating($newRating);
            }
            $em->persist($ratingObj);
        }
        $em->flush();
        return $result;
    }
    // feel free to add your own config controller methods here
}
