<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\DependencyInjection;

use Paustian\RatingsModule\DependencyInjection\Base\AbstractPaustianRatingsExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class PaustianRatingsExtension extends AbstractPaustianRatingsExtension
{
    // custom enhancements can go here
}
