<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Listener;

use Paustian\RatingsModule\Listener\Base\AbstractGroupListener;

/**
 * Event handler implementation class for group-related events.
 */
class GroupListener extends AbstractGroupListener
{
    // feel free to enhance the parent methods
}
