<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Api;

class RatingsApi
{
    static function calculateAverage($ratings, $ratingScale)
    {
        $retArray = [];
        $totalRating = 0;
        $count = count($ratings);
        foreach ($ratings as $rating) {
            $totalRating += $rating->getRating();
        }
        if (0 === $count) {
            $retArray['average'] = 0;
            $retArray['avgInt'] = 0;
            $retArray['doHalfStar'] = false;
            $retArray['emptyStars'] = $ratingScale;
        } else {
            $retArray['average'] = $totalRating/$count;
            $averageRemainder = fmod($retArray['average'], 1);
            $retArray['avgInt'] = floor($retArray['average']);
            $retArray['doHalfStar'] = ($averageRemainder >= 0.5);
            $max = $ratingScale;
            $retArray['emptyStars'] = $max - round($retArray['average']);
        }

        return $retArray;
    }

    /**
     * Adjust a Url path. This is important if Zikula is in a subdirectory.
     * 
     * @param $moduleVars
     * @param $docRoot
     */
    static function adjustUrlPath(&$moduleVars, $docRoot)
    {
        $moduleVars['iconUrl'] = $docRoot . '/' . $moduleVars['iconUrl'];
        $moduleVars['halfIconUrl'] = $docRoot . '/' . $moduleVars['halfIconUrl'];
        $moduleVars['emptyIconUrl'] = $docRoot . '/' . $moduleVars['emptyIconUrl'];
    }
}
