<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Menu;

use Paustian\RatingsModule\Menu\Base\AbstractExtensionMenu;

/**
 * This is the extension menu service implementation class.
 */
class ExtensionMenu extends AbstractExtensionMenu
{
    // feel free to add own extensions here
}
