<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Menu\Base;

use Knp\Menu\FactoryInterface;
use Knp\Menu\ItemInterface;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use Zikula\MenuModule\ExtensionMenu\ExtensionMenuInterface;
use Zikula\UsersModule\Api\ApiInterface\CurrentUserApiInterface;
use Paustian\RatingsModule\Helper\ControllerHelper;
use Paustian\RatingsModule\Helper\PermissionHelper;

/**
 * This is the extension menu service base class.
 */
abstract class AbstractExtensionMenu implements ExtensionMenuInterface
{
    /**
     * @var FactoryInterface
     */
    protected $factory;

    /**
     * @var VariableApiInterface
     */
    protected $variableApi;

    /**
     * @var CurrentUserApiInterface
     */
    protected $currentUserApi;

    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;

    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    public function __construct(
        FactoryInterface $factory,
        VariableApiInterface $variableApi,
        CurrentUserApiInterface $currentUserApi,
        ControllerHelper $controllerHelper,
        PermissionHelper $permissionHelper
    ) {
        $this->factory = $factory;
        $this->variableApi = $variableApi;
        $this->currentUserApi = $currentUserApi;
        $this->controllerHelper = $controllerHelper;
        $this->permissionHelper = $permissionHelper;
    }

    public function get(string $type = self::TYPE_ADMIN): ?ItemInterface
    {
        $contextArgs = ['api' => 'extensionMenu', 'action' => 'get'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $contextArgs);

        $permLevel = self::TYPE_ADMIN === $type ? ACCESS_ADMIN : ACCESS_READ;

        $menu = $this->factory->createItem('paustianratingsmodule' . ucfirst($type) . 'Menu');

        if (self::TYPE_ACCOUNT === $type) {
            if (!$this->currentUserApi->isLoggedIn()) {
                return null;
            }
            if (!$this->permissionHelper->hasPermission(ACCESS_OVERVIEW)) {
                return null;
            }

            if (true === $this->variableApi->get('PaustianRatingsModule', 'linkOwnRatingsOnAccountPage', true)) {
                $objectType = 'rating';
                if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_READ)) {
                    $routeParameters = ['own' => 1];
                    $menu->addChild('My ratings', [
                        'route' => 'paustianratingsmodule_' . strtolower($objectType) . '_view',
                        'routeParameters' => $routeParameters
                    ])
                        ->setAttribute('icon', 'fas fa-list-alt')
                        ->setExtra('translation_domain', 'rating')
                    ;
                }
            }

            if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                $menu->addChild('Ratings Backend', [
                    'route' => 'paustianratingsmodule_rating_adminindex'
                ])
                    ->setAttribute('icon', 'fas fa-wrench')
                ;
            }

            return 0 === $menu->count() ? null : $menu;
        }

        $routeArea = self::TYPE_ADMIN === $type ? 'admin' : '';
        if (self::TYPE_ADMIN === $type) {
            if ($this->permissionHelper->hasPermission(ACCESS_READ)) {
                $menu->addChild('Frontend', [
                    'route' => 'paustianratingsmodule_rating_index',
                ])
                    ->setAttribute('icon', 'fas fa-home')
                    ->setLinkAttribute('title', 'Switch to user area.')
                ;
            }
        } else {
            if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                $menu->addChild('Backend', [
                    'route' => 'paustianratingsmodule_rating_adminindex',
                ])
                    ->setAttribute('icon', 'fas fa-wrench')
                    ->setLinkAttribute('title', 'Switch to administration area.')
                ;
            }
        }
        
        if (
            in_array('rating', $allowedObjectTypes, true)
            && $this->permissionHelper->hasComponentPermission('rating', $permLevel)
        ) {
            $menu->addChild('Ratings', [
                'route' => 'paustianratingsmodule_rating_' . $routeArea . 'view'
            ])
                ->setLinkAttribute('title', 'Ratings list')
                ->setExtra('translation_domain', 'rating')
            ;
        }
        if ('admin' === $routeArea && $this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
            $menu->addChild('Settings', [
                'route' => 'paustianratingsmodule_config_config',
            ])
                ->setAttribute('icon', 'fas fa-wrench')
                ->setLinkAttribute('title', 'Manage settings for this application')
                ->setExtra('translation_domain', 'config')
            ;
        }

        return 0 === $menu->count() ? null : $menu;
    }

    public function getBundleName(): string
    {
        return 'PaustianRatingsModule';
    }
}
