<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use Paustian\RatingsModule\Entity\RatingSystemEntity;

/**
 * Event base class for filtering rating system processing.
 */
class AbstractFilterRatingSystemEvent extends Event
{
    /**
     * @var RatingSystemEntity Reference to treated entity instance.
     */
    protected $ratingSystem;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterRatingSystemEvent constructor.
     *
     * @param RatingSystemEntity $ratingSystem Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(RatingSystemEntity $ratingSystem, array $entityChangeSet = [])
    {
        $this->ratingSystem = $ratingSystem;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return RatingSystemEntity
     */
    public function getRatingSystem()
    {
        return $this->ratingSystem;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
