<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Event\Base;

use Paustian\RatingsModule\Entity\RatingSystemEntity;
use Symfony\Component\EventDispatcher\Event;

/**
 * Event base class for filtering rating system processing.
 */
class AbstractFilterRatingSystemEvent extends Event
{
    /**
     * @var RatingSystemEntity Reference to treated entity instance.
     */
    protected $ratingSystem;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    public function __construct(RatingSystemEntity $ratingSystem, array $entityChangeSet = [])
    {
        $this->ratingSystem = $ratingSystem;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * @return RatingSystemEntity
     */
    public function getRatingSystem()
    {
        return $this->ratingSystem;
    }

    /**
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }

    /**
     * @param array $changeSet Entity change set
     */
    public function setEntityChangeSet(array $changeSet = [])
    {
        $this->entityChangeSet = $changeSet;
    }
}
