<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Entity\Repository;

use Paustian\RatingsModule\Entity\Repository\Base\AbstractRatingRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for rating entities.
 */
class RatingRepository extends AbstractRatingRepository
{
    /**
     * @param $module
     * @param $moduleItem
     * @return array
     */

    public function getRatingForItem($module, $moduleItem){
        $qb = $this->getListQueryBuilder();
        $qb->andWhere('tbl.objectId = :objId')
            ->setParameter('objId', $moduleItem);
        $qb->andWhere('tbl.moduleName = :module')
            ->setParameter('module', $module);
        $query = $this->getQueryFromBuilder($qb);

        return $this->retrieveCollectionResult($query, false);

    }
}
