<?php
/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @link https://www.microbiologytext.com/
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Entity\Repository;

use Paustian\RatingsModule\Entity\Repository\Base\AbstractRatingSystemRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for rating system entities.
 */
class RatingSystemRepository extends AbstractRatingSystemRepository
{
    // feel free to add your own methods here, like for example reusable DQL queries
}
