<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Paustian\RatingsModule\Form\Type;

use Paustian\RatingsModule\Form\Type\Base\AbstractRatingType;

/**
 * Rating editing form type implementation class.
 */
class RatingType extends AbstractRatingType
{
    // feel free to extend the rating editing form type class here
}
