<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Controller;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Paustian\RatingsModule\Controller\Base\AbstractAjaxController;

/**
 * Ajax controller implementation class.
 *
 * @Route("/ajax")
 */
class AjaxController extends AbstractAjaxController
{
    
    /**
     *
     * @Route("/getItemListAutoCompletion", methods = {"GET"}, options={"expose"=true})
     */
    public function getItemListAutoCompletionAction(
        Request $request
    ) {
        return parent::getItemListAutoCompletionAction($request);
    }
    
    /**
     * @Route("/attachHookObject", methods = {"POST"}, options={"expose"=true})
     */
    public function attachHookObjectAction(
        Request $request
    ) {
        return parent::attachHookObjectAction($request);
    }
    
    /**
     * @Route("/detachHookObject", methods = {"POST"}, options={"expose"=true})
     */
    public function detachHookObjectAction(
        Request $request
    ) {
        return parent::detachHookObjectAction($request);
    }

    // feel free to add your own ajax controller methods here
}
