<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Controller;

use Paustian\RatingsModule\Controller\Base\AbstractRatingController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Zikula\ThemeModule\Engine\Annotation\Theme;
use Paustian\RatingsModule\Entity\RatingEntity;

/**
 * Rating controller class providing navigation and interaction functionality.
 */
class RatingController extends AbstractRatingController
{
    /**
     *
     * @Route("/admin/ratings",
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminIndexAction(
        Request $request
    ) {
        return $this->indexInternal(
            $request,
            true
        );
    }
    
    /**
     *
     * @Route("/ratings",
     *        methods = {"GET"}
     * )
     */
    public function indexAction(
        Request $request
    ) {
        return $this->indexInternal(
            $request,
            false
        );
    }
    
    /**
     *
     * @Route("/admin/ratings/view/{sort}/{sortdir}/{pos}/{num}.{_format}",
     *        requirements = {"sortdir" = "asc|desc|ASC|DESC", "pos" = "\d+", "num" = "\d+", "_format" = "html"},
     *        defaults = {"sort" = "", "sortdir" = "asc", "pos" = 1, "num" = 10, "_format" = "html"},
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminViewAction(
        Request $request,
        $sort,
        $sortdir,
        $pos,
        $num
    ) {
        return $this->viewInternal(
            $request,
            $sort,
            $sortdir,
            $pos,
            $num,
            true
        );
    }
    
    /**
     *
     * @Route("/ratings/view/{sort}/{sortdir}/{pos}/{num}.{_format}",
     *        requirements = {"sortdir" = "asc|desc|ASC|DESC", "pos" = "\d+", "num" = "\d+", "_format" = "html"},
     *        defaults = {"sort" = "", "sortdir" = "asc", "pos" = 1, "num" = 10, "_format" = "html"},
     *        methods = {"GET"}
     * )
     */
    public function viewAction(
        Request $request,
        $sort,
        $sortdir,
        $pos,
        $num
    ) {
        return $this->viewInternal(
            $request,
            $sort,
            $sortdir,
            $pos,
            $num,
            false
        );
    }
    
    //ToDo:I need to add javascript that allows an update of the rating.
    /**
     *
     * @Route("/admin/rating/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminDisplayAction(
        Request $request,
        RatingEntity $rating = null,
        $id = 0
    ) {
        return $this->displayInternal(
            $request,
            $rating,
            $id,
            true
        );
    }
    
    /**
     *
     * @Route("/rating/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET"}
     * )
     */
    public function displayAction(
        Request $request,
        RatingEntity $rating = null,
        $id = 0
    ) {
        return $this->displayInternal(
            $request,
            $rating,
            $id,
            false
        );
    }
    
    /**
     *
     * @Route("/admin/rating/edit/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"id" = "0", "_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     * @Theme("admin")
     */
    public function adminEditAction(
        Request $request
    ) {
        return $this->editInternal(
            $request,
            true
        );
    }
    
    /**
     *
     * @Route("/rating/edit/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"id" = "0", "_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     */
    public function editAction(
        Request $request
    ) {
        return $this->editInternal(
            $request,
            false
        );
    }
    
    /**
     * Process status changes for multiple items.
     *
     * @Route("/admin/ratings/handleSelectedEntries",
     *        methods = {"POST"}
     * )
     * @Theme("admin")
     */
    public function adminHandleSelectedEntriesAction(
        Request $request
    ) {
        return $this->handleSelectedEntriesActionInternal($request, true);
    }
    
    /**
     * Process status changes for multiple items.
     *
     * @Route("/ratings/handleSelectedEntries",
     *        methods = {"POST"}
     * )
     */
    public function handleSelectedEntriesAction(
        Request $request
    ) {
        return $this->handleSelectedEntriesActionInternal($request, false);
    }
    
    /**
     *
     * @Route("/rating/handleInlineRedirect/{idPrefix}/{commandName}/{id}",
     *        requirements = {"id" = "\d+"},
     *        defaults = {"commandName" = "", "id" = 0},
     *        methods = {"GET"}
     * )
     */
    public function handleInlineRedirectAction(
        $idPrefix,
        $commandName,
        $id = 0
    )
     {
        return parent::handleInlineRedirectAction($idPrefix, $commandName, $id);
    }
    
    // feel free to add your own controller methods here
}
