<?php

/**
 * Ratings.
 *
 * @copyright Timothy Paustian (Paustian)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Timothy Paustian <tdpaustian@gmail.com>.
 * @see https://www.microbiologytext.com/
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Paustian\RatingsModule\Entity\Factory\Base;

use Paustian\RatingsModule\Entity\RatingSystemEntity;
use Paustian\RatingsModule\Entity\RatingEntity;
use Paustian\RatingsModule\Helper\PermissionHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    public function __construct(
        PermissionHelper $permissionHelper
    ) {
        $this->permissionHelper = $permissionHelper;
    }

    /**
     * Initialises a given ratingSystem instance.
     *
     * @param RatingSystemEntity $entity The newly created entity instance
     *
     * @return RatingSystemEntity The updated entity instance
     */
    public function initRatingSystem(RatingSystemEntity $entity)
    {
        return $entity;
    }

    /**
     * Initialises a given rating instance.
     *
     * @param RatingEntity $entity The newly created entity instance
     *
     * @return RatingEntity The updated entity instance
     */
    public function initRating(RatingEntity $entity)
    {
        return $entity;
    }
}
